# Generated by Django 5.1.4 on 2024-12-14 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candlestick',
            fields=[
                ('ticker', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('timestamp', models.TextField(primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'db_table': 'candlesticks',
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('ticker', models.CharField(max_length=20)),
                ('timestamp', models.TextField(primary_key=True, serialize=False)),
                ('bids', models.TextField()),
                ('asks', models.TextField()),
            ],
            options={
                'db_table': 'order_book',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('ticker', models.CharField(max_length=20)),
                ('timestamp', models.TextField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_profit_loss', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_sale_fee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BollingerBands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('timestamp', models.TextField()),
                ('upper_band', models.FloatField(blank=True, null=True)),
                ('middle_band', models.FloatField(blank=True, null=True)),
                ('lower_band', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bollinger_bands',
                'abstract': False,
                'unique_together': {('ticker', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='CurrentHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('crypto_currency', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('purchase_price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_holdings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('timestamp', models.TextField()),
                ('adx', models.FloatField(blank=True, null=True)),
                ('plus_di', models.FloatField(blank=True, null=True)),
                ('minus_di', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dmi',
                'abstract': False,
                'unique_together': {('ticker', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='MACD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('timestamp', models.TextField()),
                ('macd_line', models.FloatField(blank=True, null=True)),
                ('signal_line', models.FloatField(blank=True, null=True)),
                ('histogram', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'macd',
                'abstract': False,
                'unique_together': {('ticker', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_purchase', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_sale', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('timestamp', models.TextField()),
                ('rsi', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rsi',
                'abstract': False,
                'unique_together': {('ticker', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('crypto_currency', models.CharField(max_length=25)),
                ('transaction_type', models.CharField(choices=[('BUY', '購入'), ('SELL', '売却')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('purchase_fee', models.DecimalField(decimal_places=8, max_digits=24)),
                ('sale_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
