# Generated by Django 5.1.4 on 2024-12-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bollingerbands',
            old_name='ticker',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='candlestick',
            old_name='ticker',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='dmi',
            old_name='ticker',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='macd',
            old_name='ticker',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='orderbook',
            old_name='ticker',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='ticker',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='rsi',
            old_name='ticker',
            new_name='symbol',
        ),
        migrations.AlterUniqueTogether(
            name='bollingerbands',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dmi',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='macd',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rsi',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bollingerbands',
            name='timestamp',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dmi',
            name='timestamp',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='macd',
            name='timestamp',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rsi',
            name='timestamp',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='bollingerbands',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dmi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='macd',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rsi',
            name='id',
        ),
    ]
